fix: read request body for Metro symbolication
Metro `/symbolicate` endpoint requires the request body to be available
in `req.rawBody`, which the `rawBodyMiddleware` adds.

Fixes the following error from `cli-server-api`:
    SyntaxError: Unexpected token u in JSON at position 0
        at JSON.parse (<anonymous>)
        at /Users/ville/Projects/react-native-cli/node_modules/metro/src/Server.js:1026:28